### ISSUE TITLE
Unable to set border on SmartView Duo

### ISSUE THREAD

**Issue by julien-bis** [bitfocus/companion-module-bmd-smartview#4]
I am unable to set a color as border with this module. Other commands are ok, such as Identify 15s but I can't define a color as border. Currently I can do that by sending with the nc command on a Mac Terminal. But it would great if I can do that with Companion. Any idea about what is wrong ?

**Comment by daniep01** [comment]
I have the same issue on SmartScope Duo 4K

**Comment by daniep01** [comment]
I've created a fix which should resolve this, it needs to be merged by a maintainer.

#5

**Comment by julien-bis** [comment]
I think @daniep01 is right with his suggestion. Please merge it. The last build is not relevant for this issue, the problem remain.
